### ISSUE TITLE
i cant do any commands

### ISSUE THREAD

**Issue by MiRoFreeZe** [Vrekt/QueueSniper3#2]
ive tried to do commands and it wont work

**Comment by Vrekt** [comment]
Try and kick the bot and then re add it
give it administrator permissions so it can speak anywhere
type .setup and go through that process

**Comment by PlainDevelopment** [comment]
I am having the same issue. I've kicked the bot, re-added it, gave it administrator and the bot is not replying to any commands or .setup

**Comment by Vrekt** [comment]
@PlainDevelopment this project is two years old and wasn't updated since so everything is just broken in general, sorry.
